# docker-compose.yml
version: '3.9'
services:

  mongo:
    image: mongo:7
    restart: unless-stopped
    ports: ["27017:27017"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: proppulse
    volumes: [mongo_data:/data/db]


  server:
    build: ./server
    restart: unless-stopped
    ports: ["5000:5000"]
    depends_on: [mongo]
    environment:
      NODE_ENV: development
      MONGODB_URI: mongodb://admin:password@mongo:27017/proppulse?authSource=admin
    volumes: [./server:/app, /app/node_modules]
    command: npm run dev

  ai-service:
    build: ./ai-service
    restart: unless-stopped
    ports: ["8001:8001"]
    volumes: [./ai-service:/app]

  client:
    build: ./client
    restart: unless-stopped
    ports: ["3000:3000"]
    depends_on: [server]
    volumes: [./client:/app, /app/node_modules]
    command: npm run dev

volumes:
  mongo_data:
